on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
        redis:
          - 4
          - 5
        redis-version:
          - 5
    env:
      RUBY_VERSION: ${{ matrix.ruby }}
      BUNDLE_GEMFILE: Gemfile.redis.${{ redis }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rspec
